### ISSUE TITLE
Blender stops responding when installed

### ISSUE THREAD

**Issue by ThomasAunvik** [AlexApps99/blender-rich-presence#1]
As the title says, blender stops responding when i install the addon.

Blender Version: v2.79

**Comment by AlexApps99** [comment]
I'm sorry, but this addon is still in development, as I am inexperienced with Blender addon development. This addon is broken until further progress is made.

**Comment by AlexApps99** [comment]
If you know anybody that is experienced with Blender addon development, please contact me.

**Comment by ThomasAunvik** [comment]
Easy fix, pull request at: #2
